########################################

setxkbmap -option 'ctrl:nocaps'

# ^ Use Caps Lock as Control key.

########################################

xmodmap ~/.Xmodmap

########################################

xbindkeys --file ~/.xbindkeysrc  &disown

########################################

