# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

templates:
  params:
    author-email: samboosalis@gmail.com
    author-name: Spiros Boosalis
    github-username: sboosali
    copyright: 2018 Spiros Boosalis
    module: TODO 
    
default-template: https://raw.githubusercontent.com/sboosali/configuration/master/stack/templates/spirosboosalis.hsfiles    

system-ghc: true

nix:
  enable: false # true # false
  pure: true # false
  packages:
  - zlib
  # shell-file: shell.nix

extra-include-dirs:
  - /home/sboo/.nix-profile/include

extra-lib-dirs:
  - /home/sboo/.nix-profile/lib
