########################################
# notes

# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

########################################
# templates

templates:
  params:

    author-email:    "Spiros Boosalis <samboosalis@gmail.com>"
    author-name:     Spiros Boosalis
    github-username: sboosali
    copyright:       2018 Spiros Boosalis

    module:          TODO 
    synopsis:        TODO 

default-template: ~/.stack/templates/spirosboosalis.hsfiles
# https://raw.githubusercontent.com/sboosali/configuration/master/stack/templates/spirosboosalis.hsfiles

########################################
# nix

# system-ghc: true

nix:
  enable: false 
  pure:   false
  packages:
  - zlib
  # shell-file: shell.nix

extra-include-dirs:
  - /home/sboo/.nix-profile/include

extra-lib-dirs:
  - /home/sboo/.nix-profile/lib

########################################
