########################################
# notes
########################################

# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

########################################
# nix
########################################

nix:
  enable: true
  pure:   false

system-ghc: true

extra-include-dirs:
  - /home/sboo/.nix-profile/include

extra-lib-dirs:
  - /home/sboo/.nix-profile/lib

# extra-prog-path:                     #TODO not a field.
#   - /home/sboo/.nix-profile/bin/
#   - /home/sboo/.nix-profile/libexec/

########################################
# templates
########################################

templates:
  params:

    author-email:    "Spiros Boosalis <samboosalis@gmail.com>"
    author-name:     Spiros Boosalis
    github-username: sboosali
    copyright:       2018 Spiros Boosalis

    module:          TODO 
    synopsis:        TODO 

#TODO default-template: ~/.stack/templates/spirosboosalis.hsfiles

########################################
########################################