# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

templates:
  params:
    author-email: samboosalis@gmail.com
    author-name: Spiros Boosalis
    github-username: sboosali
    copyright: 2017 Spiros Boosalis
    module: TODO 

system-ghc: true

nix:
  enable: true # false
  pure: true # false
  packages:
  - zlib
  # shell-file: shell.nix

extra-include-dirs:
  - /home/sboo/.nix-profile/include

extra-lib-dirs:
  - /home/sboo/.nix-profile/lib
