##################################################

set completion-query-items 200

# completion-query-items:
#
# default = 100
#
# > This determines when the user is queried about viewing the number of possible completions generated by the possible-completions command. It may be set to any integer value greater than or equal to zero. If the number of possible completions is greater than or equal to the value of this variable, the user is asked whether or not he wishes to view them; otherwise they are simply listed on the terminal.
#

#------------------------------------------------#

set bell-style none

# ^ one of: « none », « visible » (flash), « audible » (bell).

#------------------------------------------------#

set horizontal-scroll-mode Off

# ^ one of: « On », « Off ».
#
#   note: the letter-"O" is capitalized.

#------------------------------------------------#
# Keybindings -----------------------------------#
#------------------------------------------------#

# All of the following map the escape sequence of the 
# value contained inside the 1st argument to the 
# readline specific functions

# # for (everything?):

# "\eOd": backward-word
# "\eOc": forward-word

# # for linux console:

# "\e[1~": beginning-of-line
# "\e[4~": end-of-line
# "\e[5~": beginning-of-history
# "\e[6~": end-of-history
# "\e[3~": delete-char
# "\e[2~": quoted-insert

# # for xterm:

# "\eOH": beginning-of-line
# "\eOF": end-of-line

##################################################

# « ~/.inputrc »:
#
# • configures GNU Readline.
# • affects:
#
#     • interpreters (e.g. « ghc », « nix-repl »)
#     • completion (e.g. « cabal new-install <TAB> », « sudo apt install <TAB> »)
#     • 
#

#------------------------------------------------#

# Links:
#
# • /etc/inputrc
#
# • $ info rluserman
# • $ man 3 readline
#
# • http://www.linuxfromscratch.org/blfs/view/5.1/postlfs/inputrc.html
# • 
# • 

##################################################
