#!/bin/bash
set -eu

##################################################
# Dependencies ###################################
##################################################

command -v curl  >/dev/null
command -v jq    >/dev/null

# command -v curl  >/dev/null 2>/dev/null 
# command -v jq    >/dev/null 2>/dev/null 

##################################################
# Arguments ######################################
##################################################

Github_MyUsername="${1:-sboosali}"
WhichPage="${PAGE:-1}"

##################################################
# Variables ######################################
##################################################

Github_Hostname="https://api.github.com"
Github_Path_ListMyRepositories="users/${Github_MyUsername}/repos"

Github_Queries="per_page=100&page=${WhichPage}"

Github_URL="${Github_Hostname}/${Github_Path_ListMyRepositories}?${Github_Queries}"
Json_Query='.[].name'

##################################################
# Actions ########################################
##################################################

# echo 
# echo ----------------------------------------
# echo 
# echo "GET /${Github_Path_ListMyRepositories}"
# echo 
# echo ----------------------------------------
# echo 

curl --silent "${Github_URL}" | jq --raw-output "${Json_Query}"

# ^ NOTE « curl » exits with « 6 » when the network isn't present.
#   BUT, the command-piping (i.e. « | ») hides the exit code,
#   succeeding instead (i.e. exit-code « 0 »).

# echo 
# echo ----------------------------------------
# echo 
# echo "« curl ${Github_URL} »"
# echo 
# echo ----------------------------------------
# echo 

##################################################
# Notes ##########################################
##################################################

# ^ GET /users/:USERNAME/repos
# 
# See « https://developer.github.com/v3/repos/#list-user-repositories »
#

##################################################