#!/bin/bash
set -eu

##################################################
# Dependencies ###################################
##################################################

command -v curl
command -v jq

##################################################
# Arguments ######################################
##################################################

Github_MyUsername="${1:-sboosali}"

##################################################
# Variables ######################################
##################################################

Github_Hostname="https://api.github.com"
Github_Path_ListMyRepositories="users/${Github_MyUsername}/repos"

Github_URL="${Github_Hostname}/${Github_Path_ListMyRepositories}"
Json_Query='.[].name'

##################################################
# Actions ########################################
##################################################

# echo 
# echo ----------------------------------------
# echo 
# echo "GET /${Github_Path_ListMyRepositories}"
# echo 
# echo ----------------------------------------
# echo 

curl "${Github_URL}" | jq "${Json_Query}"

# echo 
# echo ----------------------------------------
# echo 
# echo "« curl ${Github_URL} »"
# echo 
# echo ----------------------------------------
# echo 

##################################################
# Notes ##########################################
##################################################

# ^ GET /users/:USERNAME/repos
# 
# See « https://developer.github.com/v3/repos/#list-user-repositories »
#

##################################################