#!/bin/bash
set -eu

##################################################

Message="\<\<\< $0 (1 | RR% GG% BB%) \>\>\>}"

##################################################

Output=eDPI

##################################################

function __xrandr-gamma__set() {

    xrandr --output "$Output" --gamma "${1}"

    exit 0
}

##################################################

if [ "${1:-0}" -eq 1  -a  -z "${2:-0}"  -a  -z "${3:-0}" ]
then
    __xrandr-gamma__set 1:1:1
fi

##################################################

RedString=${1:?"$Message"}
GreenString=${2:?"$Message"}
BlueString=${3:?"$Message"}

##################################################

function IsPercentage() {

    N="${1:-0}"

    [ "$N" -ge 1 -a "$N" -le 99 ]
    
    # ^ is it between 1 and 99?
}

##################################################

if IsPercentage "${RedString}"
then
    R="0.${RedString}"
else
    R="1"
fi

##############################

if IsPercentage "${GreenString}"
then
    G="0.${GreenString}"
else
    G="1"
fi

##############################

if IsPercentage "${BlueString}"
then
    B="0.${BlueString}"
else
    B="1"
fi

##############################

RGB=${R}:${G}:${B}

##################################################

__xrandr-gamma__set "${RGB}"

##################################################

# xrandr --output eDP1 --gamma "1.00":"1.00":"1.00"

##################################################
