# this file was manually overwritten, see:
# /home/sboo/configuration/locale/default-locale.sh

LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US

# the original contents (/etc/default/locale) were:
# > File generated by update-locale
# > LANG="en_US.UTF-8"
# > LC_ALL=en_US
